[project]
name = "project-build-mcp-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Nitesh Jindal", email = "niteshjindal2010@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastmcp>=4.0.3",
]

[project.scripts]
project-build-mcp-server = "project_build_mcp_server:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
